### ISSUE TITLE
Klarna payment not being completed after shipping products

### ISSUE THREAD

**Issue by folkertsmit** [mollie/PrestaShop1.7#509]
### Expected behavior

In mollie backend order should be changed from "authorized" to "voltooid (completed)"

### Actual behavior

Nothing happens

### Steps to reproduce the behavior

change order from payed to shipped.
In the module settings i selected my shipped order status.

### Environment
* PrestaShop version: 1.7.4.3 
* Mollie module version: 3.3.4 
* PHP version: 7.1.33

**Comment by loonas** [comment]
Hi @folkertsmit,

I hope that you are doing well today! Thank you for reaching out to us.
I have forwarded the issue to the developer, and we will keep you updated about the progress.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @folkertsmit,

Our team has looked into the issue, and we have noticed that you are using an outdated version of Mollie - 3.3.4.
Could you try updating your Mollie module to the latest version available? You can find it right here: https://github.com/mollie/PrestaShop1.7/releases/tag/4.4.3

Please do let us know in case the issue remains on the newest version as well.

We will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by folkertsmit** [comment]
Sorry i do have v4.4.3 - door Mollie B.V.
Met vriendelijke groet,

Folkert Smit


Op wo 19 jan. 2022 om 08:31 schreef Augustė Balčiūnaitė <
***@***.***>:

**Comment by loonas** [comment]
Thank you for your reply @folkertsmit!

I see, we appreciate the clarification. We are continuing to work on this issue in this case, and we will let you know about the progress, or in case any questions come up.

Best regards,
Invertus Support team

**Comment by folkertsmit** [comment]
So i understand its a know issue?

Met vriendelijke groet,

Folkert Smit


Op do 20 jan. 2022 om 09:17 schreef Augustė Balčiūnaitė <
***@***.***>:

**Comment by loonas** [comment]
Thank you for your reply @folkertsmit!

We were not aware of it, thank you for bringing our attention to it. Our developer has investigated the details and has fixed the issue for our upcoming release, where if "When to create the invoice" is selected default, it would change the status to completed, when the order is completed and not to shipped.
At the moment, it should still change status with the current version, although, not to Completed", but to "Klarna payment shipped".

If the status was not changed when it was shipped, it might be a different scenario, but if the status is changed to Klarna shipped, that is to be expected.
Our upcoming beta version release is planned out at the end of January. I will additionally let you know once it is released.

Let me know if you have any further details!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @folkertsmit,

I hope that you are doing well! Thank you for your patience.
The issue has been resolved in the new release, which has the beta version out, and can be downloaded here - https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta1
Let us know if you have any other questions, and any feedback regarding the release!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @folkertsmit,

Due to inactivity, I will mark this issue as resolved. Let us know if you will have any other questions!

Best regards,
Invertus Support team

**Comment by folkertsmit** [comment]
Unfortunely the updated module did not solve the problem.

When I ship my orders nothing happens in the Mollie backend. I have to put
the on sent myself.

Met vriendelijke groet,

Folkert Smit


Op di 25 jan. 2022 om 13:07 schreef Augustė Balčiūnaitė <
***@***.***>:

**Comment by loonas** [comment]
Thank you for your feedback @folkertsmit!

I have forwarded it to the developer so that he could check further. As soon as we have any news or in case we have any questions regarding further details, we will let you know!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @folkertsmit! How are you today?

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

Best regards,
Invertus Support team
